import health from "../assets/images/health.png";
import career from "../assets/images/career.png";
import descisions from "../assets/images/decisions.png";
import entrepreneur from "../assets/images/entrepreneur.png";
import learning from "../assets/images/learning.png";
import finance from "../assets/images/finance.png";
import relation from "../assets/images/relation.png";
import skills from "../assets/images/skills.png";

const Carddata = [
  {
    image: health,
    Background: "https://mentorrnow.com/assets/img/heal-h.png",
    Title: "Health",
    Para: "We believe in the power of holistic growth and development. From personal and professional growth.",
    Blog: [
      {
        Tittle: "PHYSICAL FITNESS",
        Points:
          "IT ALL STARTS WITH HEALTH. IF WE ARE FIT, OUR MIND IS AGILE. WE NEED TO BE ACTIVE TO HUSTLE. BUT IT COMES WITH A PRICE.WE HAVE TO SACRIFICE THE TASTY, OILY AND FATTY FOODS.WE HAVE TO PUSH OURSELF TO WALK, RUN, DANCE, DO YOGA OR HIT THE GYM.WE HAVE TO LEARN TO ENJOY EATING THE BLAND HEALTHY FOODS. WE HAVE TO STAY AWAY FROM JUNK FOOD, CAFFEINE ETC. HAVE TO CONSUME FRUITS, BOILED OR GRILLED PROTEINS AND ADD MORE SALADS TO OUR DIET.WE HAVE TO INCREASE OUR WATER INTAKE. WE HAVE TO HAVE PROPER REST AND ADEQUATE SLEEP.WE HAVE TO STAY AWAY FROM SMOKING, DRINKING, DRUGS OF ANY KIND AND OTHER VICES. IF THAT IS A NORM IN OUR SOCIAL CIRCLE, WE HAVE TO DISCARD THEM AND MAKE BETTER FRIENDS. HAVING NO FRIENDS IS BETTER THAN PEOPLE WHO TAKE YOU DOWN.MAKE BOOKS YOUR FRIENDS. LEARN FROM SUCCESSFUL UNKNOWN MENTORS, SOME OF THEM MAY HAVE LIVED LONG BACK TOO.WE HAVE TO GIVE THIS THE TOP PRIORITY ALWAYS.",
      },
      {
        Tittle: "MENTAL FITNESS        ",
        Points:"N TODAY’S TIMES, COMPETITION IS MUCH MORE THAN THE PREVIOUS GENERATIONS.THE WORK PRESSURES ARE MUCH MORE AND THE DEMANDING SCHEDULES ARE MUCH MORE TAXING.SO IT BECOMES PARAMOUNT TO STRUCTURE HABITS WHICH HELP US TO EASE THE STRESS.MEDITATION SHOULD BE A DAILY HABIT INCULCATED RIGHT FROM OUR CHILDHOOD.IT IS THE ONLY WAY APART FROM PRAYER PROBABLY WHEN OUR MIND GETS SOME WELL-DESERVED REST. EVEN WHILE SLEEPING THE BODY IS RESTED, NOT THE MIND. THE MIND IS STILL WORKING CREATING THE LIFE-LIKE IMAGES IN OUR DREAMS. WE SHOULD PRAY DAILY TO A HIGHER POWER FOR MORE STRENGTH TO US TO FACE OUR CHALLENGES. WE SHOULD TAP THE INFINITE RESERVOIR OF THE SUB-CONSCIOUS MIND BY COMMANDING IT WHAT WE WANT ESPECIALLY WHEN WE ARE ABOUT TO ENTER SLEEP.WE SHOULD VISUALIZE POSITIVE OUTCOMES AS WE WOULD WANT, HOWEVER SEEMINGLY UNLIKELY AND REPETITIVELY KEEP BELIEVING IN THEM DAILY.WE SHOULD KEEP AFFIRMING POSITIVELY TO OURSELVES 24x7 TO KEEP FIGHTING, STAYING HAPPY, REMINDING OURSELVES THAT WE ARE GOOD ENOUGH NO MATTER WHAT ANYONE ELSE SAYS OR DOES.",
      },
      {
        Tittle: "FINANCIAL HEALTH",
        Points:"WE HAVE TO ALWAYS ENDEAVOUR TO BE FINANCIALLY INDEPENDENT.  WE SHOULD ALWAYS HAVE ENOUGH SAVINGS TO BANK UPON IN CASE OF ANY UNFORESEEN CIRCUMSTANCES IN LIFE. OUR GOAL SHOULD ALWAYS BE TO INCREASE OUR EARNINGS AND DECREASE OUR EXPENDITURES.FRUGALITY IS A GREAT VIRTUE TO DEVELOP.WE SHOULD ALWAYS AIM VERY HIGH IN LIFE – BE IT IN A JOB OR BUSINESS. BUT WE SHOULD ALSO BE HAPPY ONCE WE HAVE ENOUGH.OUR GOALS SHOULD BE AUDACIOUS – HIGH INCENTIVES AND SALARY IN JOB AND HIGH PROFITS AND INCOME IN BUSINESS.WE SHOULD ALSO AIM FOR THE FREEDOM WHICH COMES WHEN WE KNOW WE HAVE GOOD SAVINGS SO WE CAN TRAVEL, TAKE A BREAK, INDULGE IN OTHER PASSIONS OF OURS ETC.OUR SAVINGS SHOULD BE INTELLIGENTLY INVESTED IN STOCKS ETC. WHICH GIVE US PROTECTION OF CAPITAL ALONG WITH DECENT APPRECIATION DEPENDING ON OUR RISK APPETITE, TENURE OF INVESTMENT AND INVESTMENT SIZE ETC.WE SHOULD STAY WAY FROM LOANS, CREDIT CARDS, DEBT OF ANY KIND UNLESS UNAVOIDABLE. LEVERAGE IS A STRICT NO-NO.WE SHOULD ALWAYS HAVE ADEQUATE HEALTH INSURANCE FOR ALL OUR FAMILY MEMBERS. WE SHOULD PLAN WISELY IN TERMS OF SAVINGS AND FUTURE EXPENDITURES WHEN WE ARE ABOUT TO VENTURE INTO SOME BUSINESS OF ANY KIND, ESPECIALLY WHEN WE HAVE A FAMILY.A MONTHLY SAVINGS PLAN AND INVESTMENTS INTO TAX EFFICIENT INSTRUMENTS ARE ALSO WISE TO CONSIDER.",
      },
    ],
  },
  {
    image: career,
    Background: "https://mentorrnow.com/assets/img/head-ca.png",
    Title: "Career",
    Para: " A fulfilling and satisfying career provides a sense of purpose and financial stability.",
    Blog: [
      {
        Tittle: "BUSINESS",
        Points:" DOING BUSINESS IS BOTH RISKY AND REWARDING.BUT WE SHOULD APPROACH IT IN THE RIGHT WAY. THE FREEDOM WHICH COMES WITH IT IS ALSO ENDEARING.WE SHOULD BE IN LOVE WITH THE PRODUCT OR SERVICE WHICH WE ARE ENDORSING.WE SHOUD ALWAYS BE WILLING TO GO THE EXTRA MILE TO ACHIEVE EXCELLENCE FOR OUR PRODUCT/SERVICE.WE SHOULD ALWAYS BE LOOKING TO ATTRACT LIKE-MINDED INVESTORS TO EXPAND OUR BUSINESS AT THE QUICKEST PACE WITHOUT TAKING ON MUCH LEVERAGE AND UNDUE RISKS.WE SHOULD CONSTANTLY BE UPGRADING OUR SKILLS TO MARKET OUR BUSINESS IN THE BEST DEMEANOUR. WE SHOULD CONSISTENTLY UPDATE OUR KNOWLEDGE TO IMPROVE THE QUALITY OF OUR OFFERINGS. WE SHOULD FOLLOW THE RIGHT MENTORS AND LEARN FROM THEIR MISTAKES AND BENEFIT FROM THEIR EXPERTISE. WE SHOULD CONNECT SMARTLY WITH THE RELEVANT SUPPLIERS, DISTRIBUTORS OF OUR PRODUCTS. WE SHOULD ALWAYS EXPAND OUR TEAM WITH HUNGRY PEOPLE WHO SHARE THE SIMILAR VISION BUT WHO ARE SMARTER THAN US. WE SHOULD LET ASIDE OUR EGOS AND ALWAYS LET THE BEST IDEAS WIN.",
      },
      {
        Tittle: "CAREER COUNSELING",
        Points:"IT IS VERY REWARDING TO RECOGNISE EARLY IN LIFE WHAT WE LOVE TO DO.BUT MOST PEOPLE GO THROUGH THEIR ENTIRE LIVES WITHOUT OPENING THEIR GIFT PACKAGES.THERE ARE CERTAIN TOOLS & PSYCHOMETRIC TESTS AVAILABLE WHICH CAN HELP US SHORTLIST FEW AREAS OF WORK WHICH SUITS OUR NATURE, TEMPERAMENT, EMOTIONAL QUOTIENT, INNATE TALENTS IN COGNITIVE, ANALYTICAL & LOGICAL DOMAINS ETC. OUT OF THESE AREAS WE CAN CHOOSE THE ONE(S) WHICH INTEREST US THE MOST AND NOW THE ODDS OF US SUCCEEDING AT IT INCREASE MANIFOLD. WE SHOULD ALWAYS CHOOSE TO PLAY A GAME WE ARE GOOD AT OR TRY TO INVENT A NEW ONE. IT MAY HELP US SAVE VALUABLE TIME IN OUR LIFE RATHER THAN JUST GOING THROUGH THE SOCIETAL NORMS IN PROFESSIONS AND JUST FOLLOWING THE HIT & TRIAL APPROACH.INVESTING IN A GOOD CAREER COUNSELLOR IS ALSO A WISE INVESTMENT WHICH CAN GIVE HUGELY REWARDING LONG TERM COMPUNDED RETURNS.IT’S A GOOD STRATEGY ALSO TO EXPOSE THE KIDS TO ALL THE RELEVANT SUBLECTS AT AN EARLY AGE, IDENTIFY THEIR SPECIFIC TALENTS AND INTEREST AREAS, DISCARD ALL THE REST AND THEN ONLY GOING DEEPER INTO THEIR INDIVIDUAL TALENT AND INTEREST AREAS AND REPEATING THE PROCESS UNTIL WE IDENTIFY THE KEY FOCUS CAREERS FOR EACH KID AND JUST MENTOR THEM TO EXCEL AT THEM.",
      },
      {
        Tittle: "FINDING YOUR PASSION",
        Points:" IF WE LOVE WHAT WE DO, WORK BECOMES FUN AND WE CAN WORK LONGER CONSISTENTLY BECAUSE WE LOVE IT.WE ONLY HAVE TO FOLLOW OUR HEART.A GOOD FIRST STEP CAN BE EXPLORING LOT OF DIFFERENT OPTIONS IN OUR CHILDHOOD.ONCE WE IDENTIFY A PARTICULAR DOMAIN, WE CAN SPECIALIZE FURTHER INTO SPECIFIC PROFILES AND TOPICS.INVESTMENT INTO CAREER COUNSELLING CAN BE A GOOD WAY TO IDENTIFY OR VALIDATE OUR HIDDEN GEMS.IF WE KNOW WHAT WE LIKE TO DO BUT HAVE FINANCIAL OBLIGATIONS, WE CAN TLEAST TRY WORKING IN THAT SPACE IN THE FREE TIME AND MAKE IT A SIDE PROJECT.IF WE REALLY LIKE OUR NEW HOBBY, IT WILL BLOSSOM INTO A PASSION AND ONCE IT MAKES ENOUGH FINANCIAL SENSE, IT CAN BE TURNED INTO FULL TIME OBSESSION.PURSUE EXCELLENCE, DON’T DAYDREAM ABOUT REWARDS. VISUALIZE THEM DAILY BUT FOCUS MORE ON BUILDING CONSTRUCTIVE HABITS AND PERSEVERE.ALWAYS WISH THE BEST FOR EVERYONE AND HELP EVERYONE GROW.CHOOSE YOUR PRODUCT / SERVICE TO BE PREFERABLY ONE WHICH MAKES THE LIFE OF PEOPLE BETTER, THE MORE THE MERRIER.",
      },
    ],
  },
  {
    image: learning,
    Background: "https://mentorrnow.com/assets/img/head-lear.png",
    Title: "Learning",
    Para: "Continual learning and growth help individuals stay current and prepared for new opportunities.",
    Blog: [
      {
        Tittle: "SELF-EDUCATION",
        Points:" WE HAVE TO ACQUIRE KNOWLEDGE IN THE MOST USEFUL WAY.BASIC PRIMARY EDUCATION IS A MUST IN WHICH WE LEARN TO READ, WRITE, SPEAK, DO CALCULATIONS ETC.BUT AFTER THAT WE HAVE TO ONLY EDUCATE OURSELVES ABOUT THE SUBJECTS WE ARE INTERESTED IN AND DISCARD THE REST. WE SHOULD TAKE THIS DECISION FROM THE HEART AND NOT THE BRAIN AVOIDING COMPARISONS OF MONEY LUCRATIVENESS IN THE DIFFERENT FIELDS CITING THE NET WORTHS OF TOP CHAMPIONS FROM EACH FIELD. WE DO THE THNG WE LIKE –> WE CAN MORE EASILY WORK HARDER AT IT -- > BY WORKING HARD WE AUTOMATICALLY BECOME VERY GOOD AT IT 🡪 ONCE WE BECOME VERY GOOD AT SOMETHING THERE IS HIGHER PROBABILITY OF WE EARNING MORE BY IT.ONCE WE KNOW WHAT FIELD WE LIKE, WE HAVE TO INVESTIGATE FURTHER ON THEIR SUB-FIELDS.ORGANICALLY WE WILL BE CURIIOUUS ABOUT LEARNING NEW KNOWLEDGE ABOUT THE DOMAIN WE ADORE.IF WE HAVE MULTIPLE INTERESTS, OVER A PERIOD OF TIME, WE WILL NATURALLY DRIFT TOWARDS THE TOPIC WE LOVE MORE.THE WAY OF LEARNING SHOULD ALSO BE ONE WHICH WE LIKE MOST. DIFFERENT PEOPLE RESPOND DIFFERENTLY TO AUDITORY, VISUAL LEARNINGS ETC.WE CAN OPT TO READ, LISTEN TO AUDIO BOOKS OR WATCH YOUTUBE VIDEOS ON THE TOPICS WE ARE INTERESTED IN.WE SHOULD ALWAYS HAVE HUNGRY, DRIVEN FRIENDS FROM THE SAME FIELD WITH WHOM WE CAN SHARE OUR PROGRESS, LEARN FROM THEM AND EXPONENTIALLY INCREASE IT MULTIPLE TIMES.",
      },
      {
        Tittle: "READING",
        Points:" Reading can change our life for the good.Reading can make us a better version of ourself in all respects.WE CAN Read about the lives of our idols, try to acquire the relevant knowledge and skills to become better each day.READING CAN GET US ACQUAINTED WITH NEW PERSPECTIVES AND SYSTEMS THROUGH WHICH WE CAN LEAD OUR PATH TO SUCCESS IN ALL AREAS. WE CAN LEARN FROM THE MISTAKES OF OTHERS, GET INSPIRED BY HOW THEY PAVED THEIR WAY.WE MUST STAY ABREAST OF LATEST DEVELOPMENTS & TECHNOLOGIES IN OUR AREA OF INTEREST.WE MUST ALSO READ TO IMPROVE OURSELVES IN AREAS OF OUR HEALTH, WEALTH, RELATIONSHIPS, SELF-GROWTH, WISDOM, SPIRITUALITY ETC. WE CAN ALSO READ ABOUT THE GREATEST MEN OF ALL TIME AND SNEAK A PEEK INTO THEIR MINDS AND IMPROVE OURSELVES. IF WE HAVE THE HABIT OF MARKING SOME IMPORTANT LINES OR PARAGRAPHS, THESE CAN HELP US IMMENSELY IN OUR MOMENTS OF SELF-DOUBT AND LOW CONFIDENCE",
      },
      {
        Tittle: "MENTORS",
        Points:"IT IS VERY HELPFUL TO GET A SELFLESS MENTOR IN LIFE.WE ALL NEED SOME EXPERT HELP IN SOME WALK AND PHASE OF LIFE.IT’S IMPERATIVE THAT WE FEEL THAT ALL IMPORTANT ASPECTS OF OUR LIFE ARE GOING WELL – OUR HEALTH, CAREER, RELATIONSHIPS, MENTAL HEALTH AND OUR NEED FOR SELF-REALISATION.AN EXPERIENCED, WISE MENTOR CAN GIVE DIRECTION TO OUR ENERGY AND MAKE US REACH A HIGHER VERSION OF OURSELF.HE CAN SHOW US A PLAN FOR OUR FUTURE GOALS, HELP US AVOID THE OBSTACLES AND SUPPORT US IN TOUGH TIMES.HE CAN HELP US IN MAINTAINING MOTIVATION ON A DAILY BASIS ALONG WITH A FOCUS ON OUR ABUNDANCE IN LIFE.A MENTOR CAN ALSO HELP US BUILD THE RIGHT NETWORKS FOR FUNDING REQUIREMENTS FOR OUR BUSINESS, PROFESSIONAL EXPERTS FOR SPECIFIC GOALS ETC.HE CAN ALSO SERVE AS A ROLE MODEL IN TERMS OF HOW TO COMMUNICATE WITH PEOPLE OR GROUPS, HOW TO LEAD & NURTURE TEAMS, HOW TO ELEVATE OUR KNOWLEDGE AND IMPROVE AND ADD UPON OUR SKILLS BASE.HE CAN ALSO GUIDE US ON THE IMPORTANCE OF DAILY DISCIPLINE AND THE VALUE OF SACRIFICES.HE CAN ALSO HELP US IN REALIZING OUR TRUE PASSION IN LIFE AND THEN HOW TO MAXIMISE OUR EXCELLENCE IN THAT PARTICULAR FIELD",
      },
    ],
  },
  {
    image: skills,
    Background: "https://mentorrnow.com/assets/img/head-skill.png",
    Title: "Skills",
    Para: " Developing new skills and honing existing ones leads to increased self-confidence and personal growth.",
    Blog: [
      {
        Tittle: "COMMUNICATION",
        Points:"LEARNING TO CONVEY OUR MESSAGE ENTHUSIASTICALLY AND CONFIDENTLY TO THE TARGET PERSON(S) CAN EXPONENTIALLY MULTIPLY OUR PROGRESS IN LIFE WE HAVE TO GATHER POSITIVE EXPERIENCES IN REALITY OR MIND TO BECOME BETTER AT COMMUNICATION. WE CAN IMPROVE EITHER BY TALKING TO AS MANY PEOPLE AS POSSIBLE, REVIEWING OUR PROGRESS AND IMPROVING THEREON. WE CAN ALSO PRACTISE BY MAKING A LOT OF MOBILE VIDEOS AND ALSO BY VISUALIZING OFTEN THAT WE ARE GREAT SPEAKERS. WE SHOULD ALSO KEEP ON UPDATING OUR KNOWLEDGE SO THAT WE HAVE RELEVANT STUFF TO SHARE. WE SHOULD TRY TO TALK ABOUT THE OTHER PERSON’S INTERESTS. WE SHOULD LISTEN MORE THAN TALK, THAT TOO EMPATHETICALLY. WE SHOULD TRY TO GIVE THE MAXIMUM VALUE TO THE OTHER PERSON. WE SHOULD ALWAYS BE POSITIVE AND MOTIVATE THE OTHER PERSON, LOOK FOR THE GOOD IN HIM, PRAISE HIS ACHIEVEMENTS & ALWAYS TRY TO UNDERSTAND HIS POINT OF VIEW.",
      },
      {
        Tittle: "PUBLIC SPEAKING",
        Points:"BEING CONFIDENT IN FRONT OF A CROWD CAN INCREASE OUR SUCCESS MANIFOLD. IF WE CAN MOTIVATE LARGE GROUPS OF PEOPLE SIMULTANEOUSLY AND EFFECTIVELY, IT CAN MAKE US BIG.WE SHOULD SPEAK LOUD AND SLOW WITH A LOT OF PAUSES AND ALWAYS BE ASSERTIVE.WE SHOULD USE OUR HANDS, BODY AND THE STAGE TO HELP CREATE A PICTURE IN THE AUDIENCE’S MINDS.WE SHOULD ALWAYS BE SELF-AWARE AND TRY TO START WITH FEW INTERESTING FACTS IN OUR SPEECH.WE SHOULD INTERACT WITH THE AUDIENCE AND ASK THEM QUESTIONS FREQUENTLY. WE SHOULD BE RELAXED WHILE STARTING AND RUN TO THE STAGE TO SHOW ENTHUSIASM.WE SHOULD SMILE FREQUENTLY AND HAVE A BIG BODY LANGUAGE WITH AN OPEN POSTURE.WE SHOULD ALWAYS TRY TO SPEAK ON TOPICS IN WHICH WE HAVE KNOWLEDGE OR INTEREST.WE SHOULD INCLUDE RHYMING PHRASES TO MAKE OUR MESSAGE EASILY REMEMBERABLE.WE SHOULD INITIALLY INTRODUCE OURSELVES, PRESENT OUR CREDENTIALS THEREBY VALIDATING THAT WE ARE AN AUTHORITY TO SPEAK ON THE GIVEN TOPIC.OUR BODY LANGUAGE MUST BE STILL AND CALM WITH NO FIDGETING.WE SHOULD BE PRO-ACTIVE AND WANTING TO SPEAK OURSELVES.WE SHOULD ALWAYS ADD VALUE TO THE AUDIENCE’S TIME.OUR SPEECH SHOULD ALWAYS HAVE AN INTRODUCTION, EXPLANATION WITH EXAMPLE AND A RE-ITERATING CONCLUSION AT THE END.WE SHOULD ALSO INCLUDE RELEVANT QUOTES FROM FAMOUS CELEBRITIES AND BILLIONAIRES IN OUR SPEECH.",
      },
      {
        Tittle: "NETWORKING",
        Points:" WE HAVE TO LEARN TO MAKE AN ACQUAINTANCE WITH SPECIFIC STRANGERS WHO CAN HELP US IN OUR GOALS.WE HAVE TO EXPAND OUR CIRCLE WITH DIVERSE PEOPLE OF VARIOUS EXPERTISE.WE HAVE TO ATTAIN A BIG NETWORK WITH A FAT PROSPECT BASE ALWAYS.WE CAN TIE UP WITH EXPERTS THROUGH COLD CALLING OR CONNECTING ON LINKEDIN ALONG WITH TAKING REFERENCES FROM OUR EXISTING KNOWN CIRCLE.WE HAVE TO LET GO OF OUR SHYNESS AND BE PRO-ACTIVE IN APPROACHING RELEVANT EXPERTS.WE HAVE TO TAKE AN INITIATIVE IN APPROACHING SENIOR CLIENTS IN MARQUEE EVENTS AND STRIKE A FRIENDLY BUT PROFESSIONAL SHORT CHAT TO EXCHANGE OUR CARDS TO CONTACT THEM FOR A LENGTHIER MEETING LATER.WE CAN SEARCH FOR EXPERTS WITH SPECIFIC SKILLS OR KNOWLEDGE AND BUILD A COMMUNITY WITH THEM TO PROVIDE VALUE TO THE WORLD.",
      },
    ],
  },
  {
    image: descisions,
    Background: "https://mentorrnow.com/assets/img/head-dic.png",
    Title: "Decisions",
    Para: " Making informed and deliberate decisions helps individuals achieve their goals and live the life they desire.",
    Blog: [
      {
        Tittle: "SOCIAL MEDIA",
        Points:"STAY AWAY FROM SOCIAL MEDIA AS MUCH AS POSSIBLE.ONLY PROFESSIONAL NETWORKS LIKE LINKEDIN ARE OF VALUE.FACEBOOK, INSTAGRAM ETC. ARE POWERED BY AI TO WASTE HOURS OF YOURS DAILY BY SHOWING YOU INTERESTS OF YOURS IN THE FORM OF FUNNY VIDEOS, CELEBRITIES’ FEEDS, POSTS AND IMAGES, VIDEOS ETC. OF YOUR FAVOURITE FRIENDS & FAMILY MEMBERS.ESPECIALLY AMONG TEENAGERS AND YOUNGSTERS, THEY ALSO LEAD TO COMPARISONS OF SOCIAL STATUS BY CARS, MOBILE PHONES, ATTRACTIVE SPOUSES, GRADES, HOMES, SALARIES, DESIGNATIONS ETC. WHICH HAS RISEN THE DEPRESSION LEVELS OF THE YOUTH AND CONSEQUENTLY THE SUICIDE RATES.ESPECIALLY AMONG TEENAGERS AND YOUNGSTERS, THEY ALSO LEAD TO COMPARISONS OF SOCIAL STATUS BY CARS, MOBILE PHONES, ATTRACTIVE SPOUSES, GRADES, HOMES, SALARIES, DESIGNATIONS ETC. WHICH HAS RISEN THE DEPRESSION LEVELS OF THE YOUTH AND CONSEQUENTLY THE SUICIDE RATES.",
      },
      {
        Tittle: "THE RIGHT HABITS",
        Points:" THESE ARE OF PARAMOUNT IMPORTANCE.IF INSTILLED EARLY ON IN LIFE, THEY CAN BE VERY HELPFUL. LATER ON IN LIFE, IT BECOMES INCREASINGLY DIFFICULT TO IMPLANT THEM IN OUR SYSTEM.DAILY - WORKING HARD, EXERCISING, MEDITATION, YOGA, READING RELEVANT BOOKS & NEWSPAPERS AND MAGAZINES, LEARNING NEW SKILLS BY ENROLLING INTO SPECIFIC PROGRAMS, UPGRADING OUR KNOWLEDGE, NETWORKING, LEADERSHIP & PERSUASION SKILLS, COMMUNICATION & PUBLIC SPEAKING SKILLS, CAREER COUNSELLING, FINANCIAL LITERACY, RIGHT MENTORSHIP AND HAVING THE RIGHT IDOLS, AMBITIOUS GOAL SETTING ALONG WIH AUDACIOUS PLANS TO ACHIEVE THEM – CAN BE CERTAIN GOOD TOOLS TO ACHIEVE HOLISTIC SUCCESS IN LIFE. EVERYONE LIKES THE REWARD BUT WE HAVE TO CON OUR MIND INTO WORKING HARD THIS MOMENT BY MAKING IT BELIEVE THAT CONSISTENT, HONEST EFFORT IN IS IN ITSELF THE REAL SUCCESS AS WE ONLY HAVE THE RIGHT TO IT. AFTER THAT, WE HAVE TO LEAVE THE RESULT TO THE SUPREME POWER AND SURRENDER OUR ALL KARMA EACH MOMENT TO HIM FOR ETERNAL PEACE AND BLISS. TO CHANGE OUR HABITS, WE HAVE TO CHANGE OUR REACTION TO THE CUE TO GET THE DESIRED DOPAMINE RUSH BUT IN A WAY MUCH MORE ALIGNED TO OUR LONG TERM GOALS.",
      },
    ],
  },
  {
    image: relation,
    Background: "https://mentorrnow.com/assets/img/head-rela.png",
    Title: "Relationships",
    Para: "   Strong relationships with family and friends provide support, love, and a sense of community.",
    Blog: [
      {
        Tittle: "FATHER",
        Points:
          "OUR FATHER IS OUR FIRST MENTOR.HE HAS A SELFLESS MOTIVE IN MAKING US A GOOD HUMAN, MAKING US SUCCEED IN LIFE.HE DOESN’T WANT US TO COMMIT THE SAME MISTAKES IN LIFE THAT HE DID. A FATHER CAN BE OUR BEST LONG TERM FRIEND IN LIFE. HE CAN TEACH US VALUABLE LESSONS AND USEFUL HABITS EARLY ON IN LIFE. HE CAN GUIDE US TOWARDS THE RIGHT PATH BY MAKING US READ RELEVANT BOOKS AND EXPLAINING MYSTERIOUS CONCEPTS. WE SHOULD ALWAYS RESPECT OUR FATHER AS WE CAN NEVER REPAY HIS SACRIFICES IN LIFE.",
      },
      {
        Tittle: "MOTHER",
        Points:"SHE IS THE EMBODIMENT OF THE PUREST FORM OF LOVENOONE CAN CARE FOR US AS MUCH AS OUR MOTHER.A GOOD MOTHER TEACHES US HOW TO HONOUR ALL WOMEN.SHE IS A ROLE MODEL FOR SELFLESS LOVE AND PIOUS POWER. SHE TEACHES US THE RIGHT WAY OF LIVING, CLEANLINESS, HYGIENE, CORRECT FOOD HABITS, IS VIGILANT ABOUT US STAYING AWAY FROM BAD INFLUENCES AND HABITS & COMPANY, IS MOST CONCERNED ABOUT OUR EMOTIONAL WELL-BEING AND KNOWS US BETTER THAN US OURSELVESHE IS SHAKTI AND OUR FIRST TEACHER OF UNBOUND LOVE.SHE TEACHES US THE VALUE OF TRADITIONS, THE IMPORTANCE OF RITUALS AND THE WAY TO PURITY AND THE MAGIC OF CHARITY AND SOUL CLEANSING.",
      },
      {
        Tittle: "MENTOR",
        Points: "THE RIGHT MENTOR CAN MAKE US SUCCESSFUL IN A COMPLETE SENSE. HE CAN LEAD US TO THE HIGHER POWER BY MAKING US LIVE TO OUR POTENTIAL.HE CAN MAKE US ABUNDANT BY HAVING ENOUGH WEALTH AND STILL BEING ABLE TO HELP OTHERS IN ALL RESPECTS, GIVING OUR LIFE BOTH A PURPOSE AND A DIRECTION TOO.HE CAN HELP US IN BECOMING HEALTHIER, MORE SPIRITUAL TOO ALONG WITH INCREASING OUR EMOTIONAL QUOTIENT.THE RIGHT MENTOR CAN HELP US TAKE THE RIGHT DECISIONS WHICH ARE THE BIG DIFFERIENTIATORS IN OUR LIVES.HE CAN MAKE US REALIZE OUR WHY AND HOW TO ACHIEVE IT. HE CAN ACT AS A FRIEND WHERE WE CAN SHARE OUR DEEPEST SECRETS ALONG WITH A BLIND BELIEF AND TRUST THAT HE WISHES THE BEST FOR US ALWAYS. HE WILL ALWAYS TELL US SOME CONCEPTS BUT WILL ALWAYS ENCOURAGE US TO TEST THEIR EFFECTIVENESS OURSELVES. HE WILL INCREASE OUR CONFIDENCE ALONG WITH GIVING US THE RIGHT GYANA WHICH WILL SHED OFF THE IMPURITIES FROM OUR SOUL TO MAKE IT SHINE BRIGHT AGAIN.",
      },
    ],
  },

  {
    image: entrepreneur,
    Background: "https://mentorrnow.com/assets/img/head-rela.png",
    Title: "Entrepreneurship",
    Para: "Entrepreneurship provides individuals with the opportunity to turn their ideas and passions into reality.",
    Blog: [
      {
        Tittle: "TEAM",
        Points:" A GOOD TEAM FOLLOWS AN OPEN ARCHITECTURE THE BEST IDEAS WIN IN THE BEST TEAMS, NOT THE EGOS OF THE FOUNDERS. THE ROLES OF EVERYONE ARE CLEARLY DEFINED IN A GOOD TEAM. A TEAM SHOULD HAVE EXPERTS WHO ARE CHAMPIONS IN THEIR OWN DOMAIN. A GOOD TEAM SHOULD SHARE A VISON AND A HIGHER PURPOSE OF WORKING OTHER THAN MONEY WHICH WILL FUEL THEIR PASSION DAILY TO MAKE AN EXCELLENT PRODUCT OR SERVICE.  THE TEAM MEMBERS SHOULD BE RISK TAKERS WITH A LOT OF AMBITION WHILE HAVING REALISTIC EXPECTATIONS OF SUCCESS AND THE TIME AND EFFORT REQUIRED TO ARRIVE IN LIFE.  THE TEAM MEMBERS HOULD HAVE GOOD SYNERGY ALONG WITH GREAT BONDING OFF WORK TOO PREFERABLY TO MAKE WORKING HARD FUN. CELEBRATING SMALL SUCCESSES IS ALSO HIGHLY IMPORTANT FOR A TEAM. SMALL TEAM BUILDING ACTIVITIES ALSO HELP FOSTER CAMAREDERIE TO FACILITATE LONG TERM SYMBIOTICALLY BENEFICIAL ALLIANCES.",
      },
      {
        Tittle: "VALUE",
        Points:"OUR AIM MUST ALWAYS BE CUSTOMER FIRST.WE MUST ALWAYS ENDEAVOR TO PROVIDE EXCELLENCE IN OUR PRODUCT/SERVICE.WE SHOULD ALWAYS AIM TO PRODUCE SOMETHING WHICH BENEFITS AS MANY PEOPLE AS POSSIBLE.OUR DAILY MOTIVATION SHOULD BE TO IMPROVE OUR PRODUCT/SERVICE TO CHANGE THE BETTER.WE SHOULD TAKE TARGET GROUP FEEDBACK TO IMPROVE OUR OFFERING.WE SHOULD TAKE RATINGS FROM OUR CLIENTS SERIOUSLY AND IMPLEMENT THE LEARNINGS FROM THEM INSTANTLY.WE SHOULD REWARD OUR TEAM BY INCENTIVIZING OUR TEAM TO PROVIDE CUSTOMER DELIGHT OF THE HIGHEST DEGREE.",
      },
      {
        Tittle: "FREEDOM",
        Points:
          "",
      },
    ],
  },
  {
    image: finance,
    Background: "https://mentorrnow.com/assets/img/head-fina.png",
    Title: "Financial Literacy",
    Para: "Understanding how to manage and grow personal finances is essential for financial security and stability.",
    Blog: [
      {
        Tittle: "SAVINGS",
        Points:
          " SAVINGS ARE A USEFUL BUFFER FOR US TO BANK UPON IN TIMES OF NEED.THEY ARE VERY IMPORTANT TO BE VALUE AND UNDERSTOOD FROM EARLY ON IN LIFE PREFERABLY.WE SHOULD LIMIT OUR EXPENSES, TRY TO LIVE A SIMPLE LIFE AND STAY AWAY FROM SOCIAL MEDIA COMPARISONS AND INFLUENCES.WE SHOULD UNDERSTAND OUR IMPULSES AND SEGREGATE OUR FRIVOLOUS SPENDING PATTERNS AND LEARN HOW TO CURB AND CONTROL THEM.WE SHOULD HAVE LONG TERM GOALS ATTACHED WITH OUR SAVINGS HABITS.WE SHOULD CELEBRATE AND PERIODICALLY REWARD OURSELF A BIT FOR ACHIEVING OUR SAVINGS TARGETS.CONSISTENT SAVINGS ARE MORE BENEFICIAL THAN LARGE INCOME AND HIGH EXPENDITURE IN THE LONG RUN.SAVINGS ARE ALSO A LIFELINE FOR UNFORESEEN TOUGH CIRCUMSTANCES IN LIFE."
      },
      {
        Tittle: "INVESTMENTS",
        Points:"SOUND INVESTMENTS ARE KEYS TO APPRECIATE OUR SAVINGSTHE RIGHT INVESTMENTS ARE VERY SUBJECTIVE AND INDIVIDUAL FOR EVERYONE BASED ON THEIR RISK APPETITE, TENURE AND SIZE OF INVESTMENT.AN IMPORTANT TENET OF INVESTING SHOULD BE PRESERVATION OF CAPITAL AT ALL TIMES OR IN THE LONGER RUN.THE DIFFERENT ASSET CLASSES CAN BE FIXED DEPOSITS, BONDS, INDIAN AND INTERNATIONAL STOCKS, MUTUAL FUNDS, UNLISTED STOCKS, STRUCTURES, PRIVATE EQUITY FUNDS, INSURANCE SCHEMES ETC.CERTAIN INVESTMENTS LIKE CHIT FUNDS, CRYPTOCURRENCIES ARE DEBATABLE.INVESTMENTS SHOULD BE GOAL BASED, ESPECIALLY SHOULD BE DECIDED UPON METICULOUSLY FOR EDUCATION, MARRIAGE, RETIREMENT PLANNING ETC.",
      },
    ],
  },
];

export default Carddata;
